notifications:
  irc: 
    channels:
      - "irc.esper.net#MCJS"
    on_success: change
install:
  - npm install eslint
script:
  - eslint -c .eslint.json /home/travis/build/lukecfairchild/MCJS/MCJS/*
