notifications:
  irc: 
    channels:
      - "irc.esper.net#MCJS"
    on_success: change
language: node_js
node_js:
  - "4.3"
script:
  - cd /home/travis/build/lukecfairchild/MCJS
  - npm install -s eslint
  - node ./node_modules/eslint/bin/eslint.js --rulesdir ./eslint-rules -c .eslint.json ./MCJS/*