notifications:
  irc: 
    channels:
      - "irc.esper.net#MCJS"
    on_success: change
install:
  - npm install eslint
script:
  - cd /home/travis/build/lukecfairchild
  - eslint -c .eslint.json ./MCJS/*
